// Code generated by Prismic. DO NOT EDIT.

import Image from "./Image";
import ImageWithText from "./ImageWithText";
import QuoteCallout from "./QuoteCallout";
import RichText from "./RichText";
import VideoEmbed from "./VideoEmbed";

export const components = {
	image: Image,
	image_with_text: ImageWithText,
	quote_callout: QuoteCallout,
	rich_text: RichText,
	video_embed: VideoEmbed
};